= Reliable communication

Contents: Start from where developers are (synchronous HTTP, make them understand what does it mean to communicate reliably in distributed applications).


== Data consistency &amp; transactions
- changing state in a remote system that is accessed by multiple users, that is clients
- need for synchronization, usually in transactional contexts that involve relational databases which support ACID transactions in an atomic, all-or-nothing fashion
- traditional systems communicate synchronously between client and server and between server and database
- this synchronous communication gives immediate feedback whether the action succeeded, after the server sent the response to the client
- if the transaction collides with another transaction that attempts to modify the same contents (depending on the locking strategy and isolation level), the second transaction aborts and is rolled-back
- in any way, the data stays consistent as a whole


== how "consistent" systems are actually eventually consistent
- synchronous HTTP
- timeout dilemma
- networking fallacies
- race conditions, lost updates


== distributed systems, distributed transactions, CAP theorem
- synchronous communication between more than just one backend system (e.g. microservice architecture)
- all applications have to successfully perform the desired action (maintaining all-or-nothing consistency across the applications)
- CAP (consistency, availability, network partition tolerance) theorem, it's either consistency or availability, since the network can partition
- blocking, scalability, outcome dilemma
- typically 2-phase-commit transactions
- -> not perfect solution


== Eventual consistency
- as seen, distributed transactions doen't work well in distributed systems
- giving up parts of strong consistency requirements in favor of availability (scalability) according to CAP
- eventual consistency that guarantees that "eventually" the overall system state will be consistent
- still consistency requirements in order to guarantee a successful outcome
